[project]
name = "projetopython"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.8"
dependencies = [
    "pandas>=2.0.3",
    "requests>=2.32.3",
    "seleniumbase>=4.38.3",
]
